version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: actuator-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml