global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-transactions'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["docker.host.interval:8080"]
        labels:
          application: "api-transaction"